//------------------------------------------------------------------------------
// <auto-generated>
//     Este código fue generado por una herramienta.
//     Versión de runtime:4.0.30319.42000
//
//     Los cambios en este archivo podrían causar un comportamiento incorrecto y se perderán si
//     se vuelve a generar el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace kbTools {
    using System;
    
    
    /// <summary>
    ///   Clase de recurso fuertemente tipado, para buscar cadenas traducidas, etc.
    /// </summary>
    // StronglyTypedResourceBuilder generó automáticamente esta clase
    // a través de una herramienta como ResGen o Visual Studio.
    // Para agregar o quitar un miembro, edite el archivo .ResX y, a continuación, vuelva a ejecutar ResGen
    // con la opción /str o recompile su proyecto de VS.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "15.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Idiomas {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Idiomas() {
        }
        
        /// <summary>
        ///   Devuelve la instancia de ResourceManager almacenada en caché utilizada por esta clase.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("kbTools.Idiomas", typeof(Idiomas).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Reemplaza la propiedad CurrentUICulture del subproceso actual para todas las
        ///   búsquedas de recursos mediante esta clase de recurso fuertemente tipado.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Corrigiendo Meses.
        /// </summary>
        public static string CorrigiendoMeses {
            get {
                return ResourceManager.GetString("CorrigiendoMeses", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Error.
        /// </summary>
        public static string Error {
            get {
                return ResourceManager.GetString("Error", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Agregando extension archivo de música al nombre de la carpeta.
        /// </summary>
        public static string ExtensionMusica {
            get {
                return ResourceManager.GetString("ExtensionMusica", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Limpieza.
        /// </summary>
        public static string Limpieza {
            get {
                return ResourceManager.GetString("Limpieza", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Limpiando Carpetas.
        /// </summary>
        public static string LimpiezaCarpetas {
            get {
                return ResourceManager.GetString("LimpiezaCarpetas", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Listo.
        /// </summary>
        public static string Listo {
            get {
                return ResourceManager.GetString("Listo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Archivo.
        /// </summary>
        public static string MenuArchivo {
            get {
                return ResourceManager.GetString("MenuArchivo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Español.
        /// </summary>
        public static string MenuEspañol {
            get {
                return ResourceManager.GetString("MenuEspañol", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Idioma.
        /// </summary>
        public static string MenuIdioma {
            get {
                return ResourceManager.GetString("MenuIdioma", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Ingles.
        /// </summary>
        public static string MenuIngles {
            get {
                return ResourceManager.GetString("MenuIngles", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Salir.
        /// </summary>
        public static string MenuSalir {
            get {
                return ResourceManager.GetString("MenuSalir", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Ocupado.
        /// </summary>
        public static string Ocupado {
            get {
                return ResourceManager.GetString("Ocupado", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Recursivo.
        /// </summary>
        public static string Recursivo {
            get {
                return ResourceManager.GetString("Recursivo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Renumerando archivos en una carpeta.
        /// </summary>
        public static string Renumeracion {
            get {
                return ResourceManager.GetString("Renumeracion", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Trabajando.
        /// </summary>
        public static string Trabajando {
            get {
                return ResourceManager.GetString("Trabajando", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Vaciar.
        /// </summary>
        public static string Vaciar {
            get {
                return ResourceManager.GetString("Vaciar", resourceCulture);
            }
        }
    }
}
